import React from "react";
import Head from "next/dist/shared/lib/head";
import Navbar from "./Navbar";
import { Container } from "@mui/material";

const Layout = ({ children }) => {
  return (
    <div className="flex justify-between flex-col">
      <Head>
        <title>Mini Commerce</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
      <Container className="mt-14 min-h-screen">{children}</Container>
      <footer className="bg-gray-200 text-center py-3 mt-5">
        Copyright Mini Commerce 2021
      </footer>
    </div>
  );
};

export default Layout;
